export const FETCH_MESSAGE_REQUEST = "FETCH_MESSAGE_REQUEST";
export const FETCH_MESSAGE_SUCCESS = "FETCH_MESSAGE_SUCCESS";
export const FETCH_MESSAGE_FAILURE = "FETCH_MESSAGE_FAILURE";

export const SEND_MESSAGES_REQUEST = "SEND_MESSAGES_REQUEST";
export const SEND_MESSAGES_SUCCESS = "SEND_MESSAGES_SUCCESS";
export const SEND_MESSAGES_FAILURE = "SEND_MESSAGES_FAILURE";

export const FETCH_CHAT_BY_PROJECT_REQUEST = "FETCH_CHAT_BY_PROJECT_REQUEST";
export const FETCH_CHAT_BY_PROJECT_SUCCESS = "FETCH_CHAT_BY_PROJECT_SUCCESS";
export const FETCH_CHAT_BY_PROJECT_FAILURE = "FETCH_CHAT_BY_PROJECT_FAILURE";

export const FETCH_CHAT_MESSAGE_REQUEST = "FETCHCHAT_MESSAGE_REQUEST";
export const FETCH_CHAT_MESSAGE_SUCCESS = "FETCHCHAT_MESSAGE_SUCCESS";
export const FETCH_CHAT_MESSAGE_FAILURE = "FETCHCHAT_MESSAGE_FAILURE";